baseURL = "http://example.org/"
title = "Konta's Blog"
theme = "LoveIt"
languageCode = "en"
defaultContentLanguage = "en"
languageName = "English"

paginate = 12

enableRobotsTXT = true

enableEmoji = true
 
  
[menu]
	[[menu.main]]
		weight = 0
		identifier = "ctf-write-ups"
		name = "CTF Write-ups"
		url = "/ctf-write-ups/"
		
		
[params]

  enableTooltips = false

  defaultTheme = "auto"

  gitRepo = ""

  fingerprint = ""

  dateFormat = ""

  title = ""

  description = ""

  images = [""]

  [params.header]

    desktopMode = "fixed"

    mobileMode = "auto"

    [params.header.title]

      logo = ""

      name = "Konta's Blog"

      pre = "<i class='far fa-kiss-wink-heart fa-fw' aria-hidden='true'></i>"

      post = ""

      typeit = false

  [params.footer]
    enable = true

    custom = ""

    hugo = true

    copyright = true

    author = false

    since = 2022

    icp = ""

    license= ''

  [params.section]

    paginate = 20

    dateFormat = "01-02"

    rss = 10

  [params.list]

    paginate = 20

    dateFormat = "01-02"

    rss = 10

  [params.app]

    title = "LoveIt"

    noFavicon = false

    svgFavicon = ""

    themeColor = "#ffffff"

    iconColor = "#5bbad5"

    tileColor = "#da532c"

  [params.search]
    enable = true

    type = "algolia"

    contentLength = 4000

    placeholder = ""

    maxResultLength = 10

    snippetLength = 30

    highlightTag = "em"

    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  [params.home]

    rss = 10

    [params.home.profile]
      enable = true

      gravatarEmail = ""

      avatarURL = "/images/avatar.jpg"
	  
	  

      title = "Konta"

      subtitle = "Infosec student @ ESD | CTF Player"

      typeit = true

      social = true

      disclaimer = ""

    [params.home.posts]
      enable = true

      paginate = 6

  [params.social]
    GitHub = "Konta-Freecss"
    Linkedin = "lucasb221"
    Twitter = ""
    Instagram = ""
    Facebook = ""
    Telegram = "KontaFreecss"
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Discord = ""
    DiscordInvite = ""
    Lichess = ""
    ORCID = ""
    Pleroma = ""
    Kaggle = ""
    MediaWiki= ""
    Plume = ""
    HackTheBox = "1110115"
    RootMe = ""
	TryHackMe = "Konta"
    Email = ""
    RSS = ""

  [params.page]

    hiddenFromHomePage = false

    hiddenFromSearch = false

    twemoji = false

    lightgallery = false

    ruby = true

    fraction = true

    fontawesome = true

    linkToMarkdown = true

    rssFullText = false

    [params.page.toc]

      enable = true

      keepStatic = false

      auto = true

    [params.page.code]

      copy = true

      maxShownLines = 50

    [params.page.math]
      enable = false

      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""

      blockLeftDelimiter = ""
      blockRightDelimiter = ""

      copyTex = true

      mhchem = true


    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = true
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = true
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false


 